{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "interview-backend.fullname" . }}
  labels:
    {{- include "interview-backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "interview-backend.selectorLabels" . | nindent 6 }}
{{- end }}
