{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "interview-backend.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "interview-backend.labels" . | nindent 4 }}
{{- end }}
